import { Hero } from "../models/hero.model";

export const INITIAL_HEROES: Hero[] = [
  {
    id: 1,
    name: 'SPIDERMAN',
    age: 23,
    secretIdentity: 'Peter Parker',
    birthDate: '2001-08-01',
    region: 'New York',
    nationality: 'American',
    author: 'Stan Lee',
    origin: 'comic',
    powers: ['Wall-crawling', 'Spider-sense'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/2/21/Web_of_Spider-Man_Vol_1_129-1.png',
  },
  {
    id: 2,
    name: 'SUPERMAN',
    age: 35,
    secretIdentity: 'Clark Kent',
    birthDate: '1991-06-18',
    region: 'Metropolis',
    nationality: 'Kryptonian',
    author: 'Jerry Siegel',
    origin: 'comic',
    powers: ['Flight', 'Super strength'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/3/35/Supermanflying.png',
  },
  {
    id: 3,
    name: 'BATMAN',
    age: 40,
    secretIdentity: 'Bruce Wayne',
    birthDate: '1986-02-19',
    region: 'Gotham City',
    nationality: 'American',
    author: 'Bob Kane',
    origin: 'comic',
    powers: ['Genius intellect', 'Martial arts'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c7/Batman_Infobox.jpg',
  },
  {
    id: 4,
    name: 'WONDER WOMAN',
    age: 30,
    secretIdentity: 'Diana Prince',
    birthDate: '1996-03-22',
    region: 'Themyscira',
    nationality: 'Amazonian',
    author: 'William Moulton Marston',
    origin: 'comic',
    powers: ['Super strength', 'Flight'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6b/Wonder_Woman_750.jpg',
  },
  {
    id: 5,
    name: 'MANOLITO EL FUERTE',
    age: 28,
    secretIdentity: 'Manolo',
    birthDate: '1998-05-10',
    region: 'Madrid',
    nationality: 'Spanish',
    origin: 'other',
    powers: ['Super strength'],
    imageUrl: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Manolito el Fuerte',
  },
  {
    id: 6,
    name: 'FLASH',
    age: 27,
    secretIdentity: 'Barry Allen',
    birthDate: '1999-03-14',
    region: 'Central City',
    nationality: 'American',
    author: 'Gardner Fox',
    origin: 'comic',
    powers: ['Super speed'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/e/ed/The_Flash_Family.jpg',
  },
  {
    id: 7,
    name: 'AQUAMAN',
    age: 33,
    secretIdentity: 'Arthur Curry',
    birthDate: '1993-01-08',
    region: 'Atlantis',
    nationality: 'Atlantean',
    author: 'Paul Norris',
    origin: 'movie',
    powers: ['Underwater breathing', 'Super strength'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9d/Aquaman_Rebirth_1.png',
  },
];