import { Hero } from "../models/hero.model";

export const INITIAL_HEROES: Hero[] = [
  {
    id: 1,
    name: 'Spiderman',
    age: 23,
    secretIdentity: 'Peter Parker',
    birthDate: '2001-08-01',
    region: 'New York',
    nationality: 'American',
    author: 'Stan Lee',
    origin: 'comic',
    powers: ['Wall-crawling', 'Spider-sense'],
  },
  {
    id: 2,
    name: 'Superman',
    age: 35,
    secretIdentity: 'Clark Kent',
    birthDate: '1991-06-18',
    region: 'Metropolis',
    nationality: 'Kryptonian',
    author: 'Jerry Siegel',
    origin: 'comic',
    powers: ['Flight', 'Super strength'],
  },
  {
    id: 3,
    name: 'Batman',
    age: 40,
    secretIdentity: 'Bruce Wayne',
    birthDate: '1986-02-19',
    region: 'Gotham City',
    nationality: 'American',
    author: 'Bob Kane',
    origin: 'comic',
    powers: ['Genius intellect', 'Martial arts'],
  },
  {
    id: 4,
    name: 'Wonder Woman',
    age: 30,
    secretIdentity: 'Diana Prince',
    birthDate: '1996-03-22',
    region: 'Themyscira',
    nationality: 'Amazonian',
    author: 'William Moulton Marston',
    origin: 'comic',
    powers: ['Super strength', 'Flight'],
  },
  {
    id: 5,
    name: 'Manolito el Fuerte',
    age: 28,
    secretIdentity: 'Manolo',
    birthDate: '1998-05-10',
    region: 'Madrid',
    nationality: 'Spanish',
    origin: 'other',
    powers: ['Super strength'],
  },
  {
    id: 6,
    name: 'Flash',
    age: 27,
    secretIdentity: 'Barry Allen',
    birthDate: '1999-03-14',
    region: 'Central City',
    nationality: 'American',
    author: 'Gardner Fox',
    origin: 'comic',
    powers: ['Super speed'],
  },
  {
    id: 7,
    name: 'Aquaman',
    age: 33,
    secretIdentity: 'Arthur Curry',
    birthDate: '1993-01-08',
    region: 'Atlantis',
    nationality: 'Atlantean',
    author: 'Paul Norris',
    origin: 'movie',
    powers: ['Underwater breathing', 'Super strength'],
  },
];